services:
  my-go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GoServer
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SERVER_PUBLIC_URL: "http://13.60.52.71"
    ports:
      - "3000:3000"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"